// automatically generated by the FlatBuffers compiler, do not modify

package com.netty.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
@SuppressWarnings("unused")
public final class FbBizMsg extends Table {
  public static FbBizMsg getRootAsFbBizMsg(ByteBuffer _bb) { return getRootAsFbBizMsg(_bb, new FbBizMsg()); }
  public static FbBizMsg getRootAsFbBizMsg(ByteBuffer _bb, FbBizMsg obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FbBizMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte platform() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String msgId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer msgIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer msgIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String token() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tokenAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer tokenInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String taId() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer taIdAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer taIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String msgType() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer msgTypeAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer msgTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String code() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer codeAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer codeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String msg() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer msgAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer msgInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public String msgTime() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer msgTimeAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer msgTimeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public byte msgBody(int j) { int o = __offset(20); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int msgBodyLength() { int o = __offset(20); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer msgBodyAsByteBuffer() { return __vector_as_bytebuffer(20, 1); }
  public ByteBuffer msgBodyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 20, 1); }

  public static int createFbBizMsg(FlatBufferBuilder builder,
      byte platform,
      int msgIdOffset,
      int tokenOffset,
      int taIdOffset,
      int msgTypeOffset,
      int codeOffset,
      int msgOffset,
      int msgTimeOffset,
      int msgBodyOffset) {
    builder.startObject(9);
    FbBizMsg.addMsgBody(builder, msgBodyOffset);
    FbBizMsg.addMsgTime(builder, msgTimeOffset);
    FbBizMsg.addMsg(builder, msgOffset);
    FbBizMsg.addCode(builder, codeOffset);
    FbBizMsg.addMsgType(builder, msgTypeOffset);
    FbBizMsg.addTaId(builder, taIdOffset);
    FbBizMsg.addToken(builder, tokenOffset);
    FbBizMsg.addMsgId(builder, msgIdOffset);
    FbBizMsg.addPlatform(builder, platform);
    return FbBizMsg.endFbBizMsg(builder);
  }

  public static void startFbBizMsg(FlatBufferBuilder builder) { builder.startObject(9); }
  public static void addPlatform(FlatBufferBuilder builder, byte platform) { builder.addByte(0, platform, 0); }
  public static void addMsgId(FlatBufferBuilder builder, int msgIdOffset) { builder.addOffset(1, msgIdOffset, 0); }
  public static void addToken(FlatBufferBuilder builder, int tokenOffset) { builder.addOffset(2, tokenOffset, 0); }
  public static void addTaId(FlatBufferBuilder builder, int taIdOffset) { builder.addOffset(3, taIdOffset, 0); }
  public static void addMsgType(FlatBufferBuilder builder, int msgTypeOffset) { builder.addOffset(4, msgTypeOffset, 0); }
  public static void addCode(FlatBufferBuilder builder, int codeOffset) { builder.addOffset(5, codeOffset, 0); }
  public static void addMsg(FlatBufferBuilder builder, int msgOffset) { builder.addOffset(6, msgOffset, 0); }
  public static void addMsgTime(FlatBufferBuilder builder, int msgTimeOffset) { builder.addOffset(7, msgTimeOffset, 0); }
  public static void addMsgBody(FlatBufferBuilder builder, int msgBodyOffset) { builder.addOffset(8, msgBodyOffset, 0); }
  public static int createMsgBodyVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startMsgBodyVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endFbBizMsg(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishFbBizMsgBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedFbBizMsgBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

