// automatically generated by the FlatBuffers compiler, do not modify

package com.netty.flatbuffers;

import java.nio.*;
import java.lang.*;

@SuppressWarnings("unused")
public final class FbFuturesQuotationList extends Table {
  public static FbFuturesQuotationList getRootAsFbFuturesQuotationList(ByteBuffer _bb) { return getRootAsFbFuturesQuotationList(_bb, new FbFuturesQuotationList()); }
  public static FbFuturesQuotationList getRootAsFbFuturesQuotationList(ByteBuffer _bb, FbFuturesQuotationList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FbFuturesQuotationList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FbFuturesQuotation FbFuturesQuotationList(int j) { return FbFuturesQuotationList(new FbFuturesQuotation(), j); }
  public FbFuturesQuotation FbFuturesQuotationList(FbFuturesQuotation obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int FbFuturesQuotationListLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createFbFuturesQuotationList(FlatBufferBuilder builder,
      int FbFuturesQuotationListOffset) {
    builder.startObject(1);
    FbFuturesQuotationList.addFbFuturesQuotationList(builder, FbFuturesQuotationListOffset);
    return FbFuturesQuotationList.endFbFuturesQuotationList(builder);
  }

  public static void startFbFuturesQuotationList(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addFbFuturesQuotationList(FlatBufferBuilder builder, int FbFuturesQuotationListOffset) { builder.addOffset(0, FbFuturesQuotationListOffset, 0); }
  public static int createFbFuturesQuotationListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFbFuturesQuotationListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFbFuturesQuotationList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

