// automatically generated by the FlatBuffers compiler, do not modify

package com.netty.flatbuffers;

import java.nio.*;
import java.lang.*;

@SuppressWarnings("unused")
public final class FbMsgGoodsInfoList extends Table {
  public static FbMsgGoodsInfoList getRootAsFbMsgGoodsInfoList(ByteBuffer _bb) { return getRootAsFbMsgGoodsInfoList(_bb, new FbMsgGoodsInfoList()); }
  public static FbMsgGoodsInfoList getRootAsFbMsgGoodsInfoList(ByteBuffer _bb, FbMsgGoodsInfoList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FbMsgGoodsInfoList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FbMsgGoodInfo goodsInfoList(int j) { return goodsInfoList(new FbMsgGoodInfo(), j); }
  public FbMsgGoodInfo goodsInfoList(FbMsgGoodInfo obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int goodsInfoListLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createFbMsgGoodsInfoList(FlatBufferBuilder builder,
      int goodsInfoListOffset) {
    builder.startObject(1);
    FbMsgGoodsInfoList.addGoodsInfoList(builder, goodsInfoListOffset);
    return FbMsgGoodsInfoList.endFbMsgGoodsInfoList(builder);
  }

  public static void startFbMsgGoodsInfoList(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addGoodsInfoList(FlatBufferBuilder builder, int goodsInfoListOffset) { builder.addOffset(0, goodsInfoListOffset, 0); }
  public static int createGoodsInfoListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startGoodsInfoListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFbMsgGoodsInfoList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishFbMsgGoodsInfoListBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedFbMsgGoodsInfoListBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

