// automatically generated by the FlatBuffers compiler, do not modify

package com.netty.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;

@SuppressWarnings("unused")
public final class FbMsgLoginReq extends Table {
  public static FbMsgLoginReq getRootAsFbMsgLoginReq(ByteBuffer _bb) { return getRootAsFbMsgLoginReq(_bb, new FbMsgLoginReq()); }
  public static FbMsgLoginReq getRootAsFbMsgLoginReq(ByteBuffer _bb, FbMsgLoginReq obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FbMsgLoginReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   *
   */
  public String verifyKey() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer verifyKeyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer verifyKeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  /**
   *
   */
  public String verifyCode() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer verifyCodeAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer verifyCodeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  /**
   *用户名
   */
  public String accountNo() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer accountNoAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer accountNoInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  /**
   *密码 
   */
  public String pwd() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer pwdAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer pwdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createFbMsgLoginReq(FlatBufferBuilder builder,
      int verifyKeyOffset,
      int verifyCodeOffset,
      int accountNoOffset,
      int pwdOffset) {
    builder.startObject(4);
    FbMsgLoginReq.addPwd(builder, pwdOffset);
    FbMsgLoginReq.addAccountNo(builder, accountNoOffset);
    FbMsgLoginReq.addVerifyCode(builder, verifyCodeOffset);
    FbMsgLoginReq.addVerifyKey(builder, verifyKeyOffset);
    return FbMsgLoginReq.endFbMsgLoginReq(builder);
  }

  public static void startFbMsgLoginReq(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addVerifyKey(FlatBufferBuilder builder, int verifyKeyOffset) { builder.addOffset(0, verifyKeyOffset, 0); }
  public static void addVerifyCode(FlatBufferBuilder builder, int verifyCodeOffset) { builder.addOffset(1, verifyCodeOffset, 0); }
  public static void addAccountNo(FlatBufferBuilder builder, int accountNoOffset) { builder.addOffset(2, accountNoOffset, 0); }
  public static void addPwd(FlatBufferBuilder builder, int pwdOffset) { builder.addOffset(3, pwdOffset, 0); }
  public static int endFbMsgLoginReq(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishFbMsgLoginReqBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedFbMsgLoginReqBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

